import type { Metadata } from "next"
import { Geist } from "next/font/google"
import '../styles/main.scss'
import StoreProvider from "./StoreProvider"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
})

export const metadata: Metadata = {
  title: "Book Library",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} antialiased`} >
        <StoreProvider>
          <div id="app">{children}</div>
          <div id="portal"></div>
        </StoreProvider>
      </body>
    </html>
  )
}
